
## tab
CONST_CONFIG_TAB = 0
CONST_IMPORTDATA_TAB = 1
CONST_ZROLLPITCH_TAB = 2
CONST_VALIDATION_TAB = 3
CONST_HANDEYE_TAB = 4
CONST_UNSUPERVISED_TAB = 5
CONST_EVALUATION_TAB = 6

## label type
CONST_UNEDITABLE_LABEL = 0
CONST_UNEDITABLE_LABEL2 = 1
CONST_EDITABLE_LABEL = 2
CONST_EDITABLE_LABEL2 = 3
CONST_EVAULATION_LABEL = 4
CONST_ZRP_LABEL = 5

## calibration status
CONST_IDLE = 0
CONST_PLAY = 1
CONST_PAUSE = 2

## evaluation tab radio button
CONST_CUSTOM = 1
CONST_HANDEYE = 2
CONST_UNSUPERVISED = 3
CONST_ZROLLPITCH = 4

## unsupervised lidar number radio button
CONST_SINGLE_LIDAR = 1
CONST_MULTI_LIDAR = 2

## button color
CONST_GREEN = 0
CONST_RED = 1
CONST_LIDAR = 0
CONST_GNSS = 1

## zrp tab radio button
CONST_AUTOMATIC = 1
CONST_MANUAL = 2

## RadioLabelLayout instance ID
CONST_DATAVALIDATION_USED_DATA = 1
CONST_HANDEYE_USED_DATA = 2
CONST_UNSUPERVISED_USED_DATA = 3
CONST_UNSUPERVISED_SELECT_LIDAR = 4
CONST_EVAL_SELECT_LIDAR = 5

## SpinBoxLabelLayout instance ID
CONST_CONFIG_LIDAR_NUM = 1
CONST_IMPORT_DATA_SAMPLING_INTERVER = 2
CONST_VALIDATION_MAXIMUM_ITERATION = 3
CONST_HANDEYE_MAXIMUM_ITERATION = 4
CONST_UNSUPERVISED_NUM_POINTS_PLANE_MODELING = 5
CONST_EVAL_SAMPLING_INTERVAL = 6

## DoubleSpinBoxLabelLayout instance ID
CONST_CONFIG_MINIMUM_THRESHOLD_DISTANCE = 1
CONST_CONFIG_MAXIMUM_THRESHOLD_DISTANCE = 2
CONST_CONFIG_MINIMUM_THRESHOLD_X = 3
CONST_CONFIG_MAXIMUM_THRESHOLD_X = 4
CONST_CONFIG_MINIMUM_THRESHOLD_Y = 5
CONST_CONFIG_MAXIMUM_THRESHOLD_Y = 6
CONST_CONFIG_MINIMUM_THRESHOLD_Z = 7
CONST_CONFIG_MAXIMUM_THRESHOLD_Z = 8
CONST_IMPORT_VEHICLE_MINIMUM_SPEED = 9
CONST_ZRP_MAXIMUM_X_DISTANCE = 10
CONST_ZRP_MINIMUM_X_DISTANCE = 11
CONST_ZRP_MAXIMUM_Y_DISTANCE = 12
CONST_ZRP_MINIMUM_Y_DISTANCE = 13
CONST_ZRP_MAXIMUM_Z_DISTANCE = 14
CONST_ZRP_MINIMUM_Z_DISTANCE = 15
CONST_DATAVALIDATION_TOLERANCE = 16
CONST_DATAVALIDATION_OUTLIER_DISTANCE = 17
CONST_DATAVALIDATION_HEADING_THRESHOLD = 18
CONST_DATAVALIDATION_DISTANCE_THRESHOLD = 19
CONST_HANDEYE_TOLERANCE = 20
CONST_HANDEYE_OUTLIER_DISTANCE = 21
CONST_HANDEYE_HEADING_THRESHOLD = 22
CONST_HANDEYE_DISTANCE_THRESHOLD = 23
CONST_OPTI_POINT_SAMPLING_RATIO = 24
CONST_OPTI_OUTLIER_DISTANCE = 25
CONST_EVAL_VEHICLE_MINIMUM_SPEED = 26
CONST_EVAL_DISTANCE_INTERVAL = 27
CONST_CONFIG_LENGTH = 28
CONST_CONFIG_WIDTH = 29
CONST_CONFIG_HEIGHT = 30

## SlideLabelLayouts instance ID
CONST_IMPORT_LIMIT_TIME = 1
CONST_ZRP_LIMIT_TIME = 2

## ComboBoxLabelLayout instance ID
CONST_ZRP_SELECT_LIDAR_TO_CALIB = 1
CONST_UNSUPERVISED_SELECT_LIDAR_TO_CALIB = 2
CONST_CONFIG_FRONT = 3
CONST_CONFIG_TOP = 4

## RadioWithEditLabel instance ID
CONST_EVALUATION_ZRP_RESULT_LABEL = 1
CONST_EVALUATION_RESULT_LABEL = 2

## CheckBoxListLayout instance ID
CONST_SELECT_USING_SENSOR_LIST = 1
CONST_SELECT_PRINCIPLE_SENSOR_LIST = 2

## EditLabelWithButtonLayout instance ID
CONST_CONFIG_VEHICLE_INFO = 1