
## tab
CONST_CONFIG_TAB = 0
CONST_IMPORTDATA_TAB = 1
CONST_ZROLLPITCH_TAB = 2
CONST_VALIDATION_TAB = 3
CONST_HANDEYE_TAB = 4
CONST_UNSUPERVISED_TAB = 5
CONST_EVALUATION_TAB = 6

## label type
CONST_UNEDITABLE_LABEL = 0
CONST_UNEDITABLE_LABEL2 = 1
CONST_EDITABLE_LABEL = 2
CONST_EDITABLE_LABEL2 = 3
CONST_EVAULATION_LABEL = 4
CONST_ZRP_LABEL = 5

## calibration status
CONST_IDLE = 0
CONST_PLAY = 1
CONST_PAUSE = 2

## evaluation tab radio button
CONST_CUSTOM = 1
CONST_HANDEYE = 2
CONST_UNSUPERVISED = 3
CONST_ZROLLPITCH = 4

## unsupervised lidar number radio button
CONST_SINGLE_LIDAR = 1
CONST_MULTI_LIDAR = 2

## button color
CONST_GREEN = 0
CONST_RED = 1
CONST_LIDAR = 0
CONST_GNSS = 1

## zrp tab radio button
CONST_AUTOMATIC = 1
CONST_MANUAL = 2


# Layout instance ID

## FileInputWithCheckBtnLayout instance ID
CONST_IMPORT_SELECT_LOGGING_FILE = 1

## CheckBoxListLayout instance ID
CONST_SELECT_USING_SENSOR_LIST = 1
CONST_SELECT_PRINCIPLE_SENSOR_LIST = 2

## ComboBoxLabelLayout instance ID
CONST_ZRP_SELECT_LIDAR_TO_CALIB = 1
CONST_UNSUPERVISED_SELECT_LIDAR_TO_CALIB = 2
CONST_CONFIG_FRONT = 3
CONST_CONFIG_TOP = 4

## SpinBoxLabelLayout instance ID
CONST_CONFIG_LIDAR_NUM = 1
CONST_IMPORT_DATA_SAMPLING_INTERVER = 2
CONST_VALIDATION_MAXIMUM_ITERATION = 3
CONST_HANDEYE_MAXIMUM_ITERATION = 4
CONST_UNSUPERVISED_NUM_POINTS_PLANE_MODELING = 5
CONST_EVAL_SAMPLING_INTERVAL = 6

## DoubleSpinBoxLabelLayout instance ID
CONST_CONFIG_MINIMUM_THRESHOLD_DISTANCE = 1
CONST_CONFIG_MAXIMUM_THRESHOLD_DISTANCE = 2
CONST_CONFIG_MINIMUM_THRESHOLD_X = 3
CONST_CONFIG_MAXIMUM_THRESHOLD_X = 4
CONST_CONFIG_MINIMUM_THRESHOLD_Y = 5
CONST_CONFIG_MAXIMUM_THRESHOLD_Y = 6
CONST_CONFIG_MINIMUM_THRESHOLD_Z = 7
CONST_CONFIG_MAXIMUM_THRESHOLD_Z = 8
CONST_CONFIG_LENGTH = 9
CONST_CONFIG_WIDTH = 10
CONST_CONFIG_HEIGHT = 11
CONST_IMPORT_VEHICLE_MINIMUM_SPEED = 12
CONST_ZRP_MAXIMUM_X_DISTANCE = 13
CONST_ZRP_MINIMUM_X_DISTANCE = 14
CONST_ZRP_MAXIMUM_Y_DISTANCE = 15
CONST_ZRP_MINIMUM_Y_DISTANCE = 16
CONST_ZRP_MAXIMUM_Z_DISTANCE = 16
CONST_ZRP_MINIMUM_Z_DISTANCE = 17
CONST_DATAVALIDATION_TOLERANCE = 18
CONST_DATAVALIDATION_OUTLIER_DISTANCE = 19
CONST_DATAVALIDATION_HEADING_THRESHOLD = 20
CONST_DATAVALIDATION_DISTANCE_THRESHOLD = 21
CONST_DATAVALIDATION_MAXIMUM_Z_DISTANCE = 22
CONST_DATAVALIDATION_MINIMUM_Z_DISTANCE = 23
CONST_HANDEYE_TOLERANCE = 24
CONST_HANDEYE_OUTLIER_DISTANCE = 25
CONST_HANDEYE_HEADING_THRESHOLD = 26
CONST_HANDEYE_DISTANCE_THRESHOLD = 27
CONST_HANDEYE_MAXIMUM_Z_DISTANCE = 28
CONST_HANDEYE_MINIMUM_Z_DISTANCE = 29
CONST_OPTI_POINT_SAMPLING_RATIO = 30
CONST_OPTI_OUTLIER_DISTANCE = 31
CONST_OPTI_MAXIMUM_Z_DISTANCE = 32
CONST_OPTI_MINIMUM_Z_DISTANCE = 33
CONST_EVAL_VEHICLE_MINIMUM_SPEED = 34
CONST_EVAL_DISTANCE_INTERVAL = 35
CONST_EVAL_MAXIMUM_Z_DISTANCE = 36
CONST_EVAL_MINIMUM_Z_DISTANCE = 37
CONST_EVAL_VOXEL_GRID_SIZE = 38
CONST_CONFIG_REF_X = 39
CONST_CONFIG_REF_Y = 40
CONST_CONFIG_REF_Z = 41
CONST_CONFIG_REF_ROLL = 42
CONST_CONFIG_REF_PITCH = 43
CONST_CONFIG_REF_YAW = 44

## SlideLabelLayouts instance ID
CONST_IMPORT_LIMIT_TIME = 1
CONST_ZRP_LIMIT_TIME = 2
CONST_EVAL_LIMIT_TIME = 3

## RadioLabelLayout instance ID
CONST_DATAVALIDATION_USED_DATA = 1
CONST_HANDEYE_USED_DATA = 2
CONST_UNSUPERVISED_USED_DATA = 3
CONST_UNSUPERVISED_SELECT_LIDAR = 4
CONST_EVAL_SELECT_LIDAR = 5

## EditLabelWithButtonLayout instance ID
CONST_CONFIG_VEHICLE_INFO = 1

## LabelWithDoubleSpinBoxsLayout instance ID
CONST_IMPORT_GNSS_INITIAL_POSE = 1
CONST_IMPORT_MOTION_INITIAL_POSE = 2

## RadioWithEditLabel instance ID
CONST_EVALUATION_ZRP_RESULT_LABEL = 1
CONST_EVALUATION_RESULT_LABEL = 2

## LabelWithSliderLayout instance ID
CONST_CONFIG_TRANSPARENT = 1
CONST_XYYAW_TRANSPARENT = 2
CONST_EVAL_TRANSPARENT = 3
CONST_VIEW_TRANSPARENT = 4