## QUniqDoubleSpinBox instance ID
CONST_IMPORT_GNSS_EAST = 1
CONST_IMPORT_GNSS_NORTH = 2
CONST_IMPORT_GNSS_HEADING = 3
CONST_IMPORT_MOITION_EAST = 4
CONST_IMPORT_MOITION_NORTH = 5
CONST_IMPORT_MOITION_HEADING = 6
